version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  rabbitmq:
    image: "rabbitmq"
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
  callback_receiver:
    image: milkywan/cyborgbackup:latest
    command: bash -c "python /cyborgbackup/manage.py run_callback_receiver -v 3"
    volumes:
      - ./src:/cyborgbackup
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
  channel_workers:
    image: milkywan/cyborgbackup:latest
    command: bash -c 'python /cyborgbackup/manage.py runworker --only-channels websocket.*'
    volumes:
      - ./src:/cyborgbackup
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
  web:
    image: milkywan/cyborgbackup:latest
    command: bash -c "python /cyborgbackup/manage.py migrate --noinput && python /cyborgbackup/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/cyborgbackup
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
  celery:
    image: milkywan/cyborgbackup:latest
    command: celery -A cyborgbackup worker -E
    volumes:
      - ./src:/cyborgbackup
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
  celery_beat:
    image: milkywan/cyborgbackup:latest
    command: celery -A cyborgbackup beat
    volumes:
      - ./src:/cyborgbackup
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
